#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    May 25, 2021 12:39:00 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global TOKEN_FROM_CHOICE
    TOKEN_FROM_CHOICE = tk.StringVar()

    global TOKEN_CUSTOM_FROM_CHOICE
    TOKEN_CUSTOM_FROM_CHOICE = 'CUSTOM'

    global TOKEN_TO_CHOICE
    TOKEN_TO_CHOICE = tk.StringVar()

    global TOKEN_CUSTOM_TO_CHOICE
    TOKEN_CUSTOM_TO_CHOICE = 'CUSTOM'

    global PERCENTAGE
    PERCENTAGE = tk.StringVar()

    global TAKE_PROFIT_ACTIVATED
    TAKE_PROFIT_ACTIVATED = tk.BooleanVar()

    global STOP_LOSS_ACTIVATED
    STOP_LOSS_ACTIVATED = tk.BooleanVar()

    global LIMIT_TP
    LIMIT_TP = tk.StringVar()

    global STOP_LOSS
    STOP_LOSS = tk.StringVar()

    global PRICE
    PRICE = tk.StringVar()

    global UNITY
    UNITY = tk.StringVar()
    

    # global PRICE_WORDING
    # PRICE_WORDING = PRICE+" ZEBS"

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import pancake_swap_bot_ui
    pancake_swap_bot_ui.vp_start_gui()




